{% set name = "xarpes" %}
{% set version = "0.4.0" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e23db1d9babcbca639ae7f18bc2552a5734b124415e8dca1b7fbb502ea7e891b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - igor2 >=0.5.8
    - jupyterlab
    - jupytext
    - matplotlib-base
    - numpy
    - scipy
    - lmfit
    - pyqt
    - ipympl >=0.9.3
    - ipywidgets >=8.1.5
    - ipykernel <6.32.0

test:
  imports:
    - xarpes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://xarpes.readthedocs.io
  summary: Extraction from angle resolved photoemission spectra
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TeetotalingTom
    - janberges
    - sponce24
