{% set name = "xarpes" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: beefeeb9c6486097a961ec7cb5e1c8e64cd661e3db0f9ed7bdc9756873f7983b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - igor2
    - jupyterlab
    - jupytext
    - matplotlib-base
    - numpy
    - scipy
    - lmfit
    - xarray
    - pyqt

test:
  imports:
    - xarpes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://xarpes.github.io
  summary: Extraction from angle resolved photoemission spectra
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TeetotalingTom
    - janberges
    - sponce24
