{% set name = "xarpes" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5d15bbe87f7dc1e7a7d0d5a7a03910da8c264d2f3033fa40c68010e2ab1b2a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - flit-core >=3.4
    - pip
  run:
    - python >=3.5
    - igor2
    - jupyterlab
    - jupytext
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - xarpes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://xarpes.github.io
  summary: Extraction from angle resolved photoemission spectra
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TeetotalingTom
    - janberges
    - sponce24
