{% set name = "xarpes" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df2db6162e9d3f2c4db1fd0625f78b2b3f973b8abf1401ba898c1575f53c617c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - flit-core >=3.4
    - pip
  run:
    - python >=3.5
    - igor2
    - jupyterlab
    - jupytext
    - matplotlib-base
    - numpy
    - scipy
    - lmfit

test:
  imports:
    - xarpes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://xarpes.github.io
  summary: Extraction from angle resolved photoemission spectra
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TeetotalingTom
    - janberges
    - sponce24
